### ISSUE TITLE
Midair Only Unloading

### ISSUE THREAD

**Issue by r4g3z** [x0rnn/minqlx-plugins#9]
Hi, @x0rnn

Thanks for the awesome plug-ins.

There is an issue in the midair only plug in. While it loads OK. Once loaded its impossible to unload it and revert to normal FFA mode. You continue to be stuck with unlimited rockets and if you change map you get one more weapon that's starting weapon but then unlimited ammo and rockets!

Restarting any FFA map doesn't fix the issue...

Only way is to restart server!

Pls help..

Thanks

**Comment by x0rnn** [comment]
I don't have QL installed anymore, but it's probably because the server cvars get changed (see the last 15 lines of the plugin), and after unloading they stay changed. I don't think there is a way to undo the settings after unloading (point of the plugin was never to be unloaded anyway), except manually changing them or by executing a server config to change them to their default values.
